[tool]
id = "com.thelightphone.weather"
label = "Weather"
versionCode = 4
versionName = "4.0.0"
permissions = ["android.permission.INTERNET"]
# change if you run this on the emulator!
# serverPackage = "com.thelightphone.sdk.emulator"
serverPackage = "com.lightos"
