[tool]
id            = "dev.tyler.wiki"
label         = "Wiki"
versionCode   = 1
versionName   = "0.1.0"
permissions   = ["android.permission.INTERNET"]
orientation   = "portrait"
serverPackage = "com.lightos"
# serverPackage = "com.thelightphone.sdk.emulator"
